server:
  port: 8081
  error:
    include-exception: true
    include-message: always
spring:
  webflux:
    base-path: /api/v1
  application:
    name: "autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: "${SPRING_R2DBC_URL}"
    username: "${SPRING_R2DBC_USERNAME}"
    password: "${SPRING_R2DBC_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
app:
  secret:
    key: "${SECRET_KEY}"
